const projectsData = [
  {
    id: "corpo-4",
    title: "Cinematic Film & Color Grade // Corpo 4",
    category: "commercial",
    categoryLabel: "Comercial & Cinema",
    videoPreview: "media/lowres/corpo_4.mp4",
    videoSrc: "media/corpo_4.mp4",
    aspectRatio: "horizontal",
    tag: "4K Cinema",
    views: "Destaque",
    retention: "Color Grading",
    description: "Edição cinematográfica de alta densidade visual com correção de cor e sound design imersivo.",
    software: ["Premiere", "After Effects", "Sound FX"]
  },
  {
    id: "vilgner-tattoo",
    title: "Vilgner Tattoo 2 // Dynamic Reel",
    category: "reels",
    categoryLabel: "Reels / TikTok",
    videoPreview: "media/lowres/montagem_vilgner_tattoo_2_v02_1.mp4",
    videoSrc: "media/montagem_vilgner_tattoo_2_v02_1.mp4",
    aspectRatio: "vertical",
    tag: "Viral Edit",
    views: "Destaque",
    retention: "Alta Retenção",
    description: "Edição vertical dinâmica com transições com máscara, sound design punchy e ritmo acelerado.",
    software: ["Premiere", "After Effects"]
  },
  {
    id: "jackson-teixeira",
    title: "Jackson Teixeira // Tum Tum Showcase",
    category: "youtube",
    categoryLabel: "YouTube & Long Form",
    videoPreview: "media/lowres/jackson_teixeira_tumtum.mp4",
    videoSrc: "media/jackson_teixeira_tumtum.mp4",
    aspectRatio: "horizontal",
    tag: "High Energy",
    views: "Destaque",
    retention: "Sound Design",
    description: "Montagem narrativa de alto engajamento, sincronia musical e motion graphics personalizados.",
    software: ["Premiere", "After Effects", "Photoshop"]
  },
  {
    id: "vilgner-setembro",
    title: "Vilgner Setembro // Motion & Cut",
    category: "reels",
    categoryLabel: "Reels / TikTok",
    videoPreview: "media/lowres/vilgner_setembro_24.mp4",
    videoSrc: "media/vilgner_setembro_24.mp4",
    aspectRatio: "vertical",
    tag: "Short Form",
    views: "Destaque",
    retention: "Cortes Rápidos",
    description: "Edição curta de alto impacto com efeitos visuais e texturas estilizadas.",
    software: ["Premiere", "After Effects"]
  },
  {
    id: "script-75",
    title: "Script 75 // Talking Head & B-Roll",
    category: "youtube",
    categoryLabel: "YouTube / Infoproduto",
    videoPreview: "media/lowres/script_75_c0636_3.mp4",
    videoSrc: "media/script_75_c0636_3.mp4",
    aspectRatio: "vertical",
    tag: "Infoproduto",
    views: "Destaque",
    retention: "Alta Retenção",
    description: "Edição para criadores e infoprodutores com legendas dinâmicas, pop-ups visuais e inserts de b-roll.",
    software: ["Premiere", "After Effects"]
  },
  {
    id: "script-82",
    title: "Script 82 // Storytelling & Pacing",
    category: "motion",
    categoryLabel: "Motion & Storytelling",
    videoPreview: "media/lowres/script_82_c0640_1.mp4",
    videoSrc: "media/script_82_c0640_1.mp4",
    aspectRatio: "vertical",
    tag: "Motion FX",
    views: "Destaque",
    retention: "Animações 2D",
    description: "Storytelling visual fluido com animações tipográficas, sonoplastia precisa e ritmo envolvente.",
    software: ["After Effects", "Premiere"]
  },
  {
    id: "scrip-89",
    title: "Script 89 // Hook & Retention Cut",
    category: "reels",
    categoryLabel: "Reels / TikTok",
    videoPreview: "media/lowres/scrip_89_c0681_1.mp4",
    videoSrc: "media/scrip_89_c0681_1.mp4",
    aspectRatio: "vertical",
    tag: "Hook 3s",
    views: "Destaque",
    retention: "Alta Retenção",
    description: "Gancho inicial de 3 segundos focado em retenção para anúncios e conteúdo orgânico.",
    software: ["Premiere", "Sound Design"]
  }
];
